### ISSUE TITLE
逻辑问题：Cookie错误会直接显示全部播放完毕，而不是告诉应当更新Cookie

### ISSUE THREAD

**Issue by SwordLikeRain** [LetMeFly666/YuketangAutoPlayer#1]
如题

**Comment by LetMeFly666** [comment]
感谢反馈~

预计今日完成

**Comment by LetMeFly666** [comment]
https://github.com/LetMeFly666/YuketangAutoPlayer/commit/90feea5f8d3f54bc160d60152c198013ea73bb16  中新增了“cookie”设置失败时的“临时扫码登录”功能👍
